# constants
RND_SEED = 77
MEM_THRES = 1.0
WEIGHT = 1.0
FORGETTING = 0.05
INTERFERENCE = 0.005
ULENS = [2, 3]
TPS_ORDER = 1
OUT_DIR = "data/out/"
EXAMPLES_OUT_DIR = "./out/"
GRAPH_SEP = " | "
STM_DECAY_RATE = 1000
LTM_DECAY_RATE = 100
CHILDES_REPO = "C:/Users/matti/OneDrive/Desktop/DOTT/CHILDES/"
